export interface ResultCalculate {
    knot: number,
    h: number,
    fita: number,
    ms: number,
    rn: number,
    cf: number,
    rf: number
    k1: number,
    rapp: number,
    fn: number,
    m2: number,
    rw: number,
    fni: number,
    rb: number,
    fnt:number,
    c6: number,
    rtr: number,
    ra: number,
    rt: number,
    RAf: number,
    seaMargin: number,
    tops:number,
    aops:number,
    radis:number,
    drafKn:number,
    knotVair: number, 
    msVair: number, 
    raa: number,
    ywr: number,
    actualKnot: number,
    temp: number,
    efekSuhuGaram: string, 
    efekGelombang: string,
    stawaveMethod: string
  }